### ISSUE TITLE
Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

### ISSUE THREAD

**Issue by patt0** [GoogleDeveloperExperts/experts-app-web#123]
https://github.com/GoogleDeveloperExperts/experts-app-backend/issues/32

**Comment by justinribeiro** [comment]
Humm that's problematic. To @tbassetto point in the other ticket, it is because of "Settings > Privacy > Content Settings > Cookies > Block sites from setting any data" being set. 

I don't have a quick fix for this. Google Sign-In is the issue here and because they don't have a check in that code (there is not a feature detect available per https://bugs.chromium.org/p/chromium/issues/detail?id=426206 and https://bugs.chromium.org/p/chromium/issues/detail?id=357625), I'm not sure if I can trap this. 

Let me dig around a bit.
