### ISSUE TITLE
Navigation menus not responding sometimes

### ISSUE THREAD

**Issue by reicek** [GoogleDeveloperExperts/experts-app-web#70]
Sometimes selecting a new section on the navigation menu doesn't trigger any action.

This bug seems to be random.

**Comment by LostInBrittany** [comment]
It seems to be a problem when passing from _Profile_ To _Map_ (reproductible, I'm trying to squash it), trying to find other reproductible bugs

**Comment by LostInBrittany** [comment]
It was a silly problem, so silly that I spent two hours trying to find it, because I didn't think of the evident cause...

We had navigation done with `paper-buttons` that had an `a` element inside. But the buttons didn't do anything, their `on-click` listener wasn't configured. So in order to navigate you needed to click exactly on the label of the button, if you clicked outside it you had the button visual cue but no navigation was done. 

I've changed the navigation to be done exclusively via the buttons, no links, and now it works like a charm.

**Comment by reicek** [comment]
Kudos @LostInBrittany !
